import Skill from "./Skill.js";

export const SkillDatabase = {
  "Chicote de Vinha": new Skill({ name: "Chicote de Vinha", type: "damage", element: "grass", power: 35, cowndown: 8, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Pó do Sono": new Skill({ name: "Pó do Sono", type: "status", element: "grass", power: 10, cowndown: 12, spriteSkillList: ["56827","56827"], targetArea: "3x3" }),
  "Pó Venenoso": new Skill({ name: "Pó Venenoso", type: "status", element: "poison", power: 15, cowndown: 10, spriteSkillList: ["56827","56827"], targetArea: "3x3" }),
  "Raio Solar": new Skill({ name: "Raio Solar", type: "damage", element: "grass", power: 90, cowndown: 25, spriteSkillList: ["56827","56827"], targetArea: "5x5" }),
  "Brasas": new Skill({ name: "Brasas", type: "damage", element: "fire", power: 30, cowndown: 8, spriteSkillList: ["56827","56827"], targetArea: "3x3" }),
  "Arranhão": new Skill({ name: "Arranhão", type: "damage", element: "normal", power: 20, cowndown: 5, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Lança-Chamas": new Skill({ name: "Lança-Chamas", type: "damage", element: "fire", power: 70, cowndown: 18, spriteSkillList: ["56827","56827"], targetArea: "5x5" }),
  "Voo": new Skill({ name: "Voo", type: "damage", element: "flying", power: 60, cowndown: 15, spriteSkillList: ["56827","56827"], targetArea: "line" }),
  "Jato de Água": new Skill({ name: "Jato de Água", type: "damage", element: "water", power: 35, cowndown: 8, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Giro Rápido": new Skill({ name: "Giro Rápido", type: "damage", element: "normal", power: 30, cowndown: 10, spriteSkillList: ["56827","56827"], targetArea: "3x3" }),
  "Hidro Bomba": new Skill({ name: "Hidro Bomba", type: "damage", element: "water", power: 90, cowndown: 25, spriteSkillList: ["56827","56827"], targetArea: "5x5" }),
  "Investida": new Skill({ name: "Investida", type: "damage", element: "normal", power: 25, cowndown: 5, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Endurecer": new Skill({ name: "Endurecer", type: "buff", element: "normal", power: 10, cowndown: 8, spriteSkillList: ["56827","56827"], targetArea: "self" }),
  "Confusão": new Skill({ name: "Confusão", type: "damage", element: "psychic", power: 40, cowndown: 12, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Ferrão": new Skill({ name: "Ferrão", type: "damage", element: "bug", power: 20, cowndown: 5, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Fúria do Ferrão": new Skill({ name: "Fúria do Ferrão", type: "damage", element: "bug", power: 55, cowndown: 15, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Rajada de Vento": new Skill({ name: "Rajada de Vento", type: "damage", element: "flying", power: 30, cowndown: 8, spriteSkillList: ["56827","56827"], targetArea: "line" }),
  "Ataque Aéreo": new Skill({ name: "Ataque Aéreo", type: "damage", element: "flying", power: 50, cowndown: 12, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Furacão": new Skill({ name: "Furacão", type: "damage", element: "flying", power: 80, cowndown: 22, spriteSkillList: ["56827","56827"], targetArea: "5x5" }),
  "Mordida": new Skill({ name: "Mordida", type: "damage", element: "dark", power: 35, cowndown: 8, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Super Mordida": new Skill({ name: "Super Mordida", type: "damage", element: "dark", power: 55, cowndown: 14, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Terremoto": new Skill({ name: "Terremoto", type: "damage", element: "ground", power: 85, cowndown: 22, spriteSkillList: ["56827","56827"], targetArea: "5x5" }),
  "Chifre Duplo": new Skill({ name: "Chifre Duplo", type: "damage", element: "normal", power: 45, cowndown: 10, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Canto": new Skill({ name: "Canto", type: "status", element: "fairy", power: 15, cowndown: 18, spriteSkillList: ["56827","56827"], targetArea: "3x3" }),
  "Explosão Lunar": new Skill({ name: "Explosão Lunar", type: "damage", element: "fairy", power: 80, cowndown: 25, spriteSkillList: ["56827","56827"], targetArea: "5x5" }),
  "Chama": new Skill({ name: "Chama", type: "damage", element: "fire", power: 30, cowndown: 8, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Lança-chamas": new Skill({ name: "Lança-chamas", type: "damage", element: "fire", power: 70, cowndown: 18, spriteSkillList: ["56827","56827"], targetArea: "5x5" }),
  "Roda de Fogo": new Skill({ name: "Roda de Fogo", type: "damage", element: "fire", power: 50, cowndown: 12, spriteSkillList: ["56827","56827"], targetArea: "3x3" }),
  "Explosão de Fogo": new Skill({ name: "Explosão de Fogo", type: "damage", element: "fire", power: 90, cowndown: 25, spriteSkillList: ["56827","56827"], targetArea: "5x5" }),
  "Dança das Penas": new Skill({ name: "Dança das Penas", type: "status", element: "flying", power: 0, cowndown: 15, spriteSkillList: ["56827","56827"], targetArea: "3x3" }),
  "Ataque de Asa": new Skill({ name: "Ataque de Asa", type: "damage", element: "flying", power: 40, cowndown: 8, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Bug Bite": new Skill({ name: "Bug Bite", type: "damage", element: "bug", power: 40, cowndown: 8, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Tiro de Seda": new Skill({ name: "Tiro de Seda", type: "status", element: "bug", power: 0, cowndown: 10, spriteSkillList: ["56827","56827"], targetArea: "3x3" }),
  "Picada": new Skill({ name: "Picada", type: "damage", element: "bug", power: 20, cowndown: 5, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Pó Paralisante": new Skill({ name: "Pó Paralisante", type: "status", element: "bug", power: 0, cowndown: 12, spriteSkillList: ["56827","56827"], targetArea: "3x3" }),
  "Aqua Tail": new Skill({ name: "Aqua Tail", type: "damage", element: "water", power: 60, cowndown: 14, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Dança da Chuva": new Skill({ name: "Dança da Chuva", type: "status", element: "water", power: 0, cowndown: 20, spriteSkillList: ["56827","56827"], targetArea: "self" }),
  "Jato d'Água": new Skill({ name: "Jato d'Água", type: "damage", element: "water", power: 35, cowndown: 8, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Furacão": new Skill({ name: "Furacão", type: "damage", element: "flying", power: 80, cowndown: 22, spriteSkillList: ["56827","56827"], targetArea: "5x5" }),
  "Ataque Aéreo": new Skill({ name: "Ataque Aéreo", type: "damage", element: "flying", power: 50, cowndown: 12, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Canção": new Skill({ name: "Canção", type: "status", element: "fairy", power: 10, cowndown: 15, spriteSkillList: ["56827","56827"], targetArea: "3x3" }),
  "Canção Mortal": new Skill({ name: "Canção Mortal", type: "status", element: "fairy", power: 25, cowndown: 30, spriteSkillList: ["56827","56827"], targetArea: "5x5" }),
  "Supersônico": new Skill({ name: "Supersônico", type: "status", element: "normal", power: 15, cowndown: 12, spriteSkillList: ["56827","56827"], targetArea: "3x3" }),
  "Absorver": new Skill({ name: "Absorver", type: "damage", element: "grass", power: 25, cowndown: 6, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Pétala Solar": new Skill({ name: "Pétala Solar", type: "damage", element: "grass", power: 70, cowndown: 18, spriteSkillList: ["56827","56827"], targetArea: "5x5" }),
  "Escavação": new Skill({ name: "Escavação", type: "damage", element: "ground", power: 50, cowndown: 12, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Garra Furiosa": new Skill({ name: "Garra Furiosa", type: "damage", element: "normal", power: 55, cowndown: 12, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Golpe Karate": new Skill({ name: "Golpe Karate", type: "damage", element: "fighting", power: 45, cowndown: 10, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Fúria": new Skill({ name: "Fúria", type: "damage", element: "fighting", power: 60, cowndown: 15, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Bolhas": new Skill({ name: "Bolhas", type: "damage", element: "water", power: 30, cowndown: 8, spriteSkillList: ["56827","56827"], targetArea: "3x3" }),
  "Hipnose": new Skill({ name: "Hipnose", type: "status", element: "psychic", power: 20, cowndown: 18, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Soco Dinâmico": new Skill({ name: "Soco Dinâmico", type: "damage", element: "fighting", power: 85, cowndown: 22, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Teleporte": new Skill({ name: "Teleporte", type: "utility", element: "psychic", power: 10, cowndown: 20, spriteSkillList: ["56827","56827"], targetArea: "self" }),
  "Psíquico": new Skill({ name: "Psíquico", type: "damage", element: "psychic", power: 80, cowndown: 22, spriteSkillList: ["56951","56952"], targetArea: "5x5" }),
  "Choque do Trovão": new Skill({ name: "Choque do Trovão", type: "damage", element: "electric", power: 40, cowndown: 10, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Cauda de Ferro": new Skill({ name: "Cauda de Ferro", type: "damage", element: "steel", power: 55, cowndown: 14, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Impacto Relâmpago": new Skill({ name: "Impacto Relâmpago", type: "damage", element: "electric", power: 75, cowndown: 20, spriteSkillList: ["56827","56827"], targetArea: "line" }),
  "Splash": new Skill({ name: "Splash", type: "utility", element: "water", power: 1, cowndown: 1, spriteSkillList: ["56827","56827"], targetArea: "self" }),
  "Cura": new Skill({ name: "Cura", type: "heal", element: "normal", power: 60, cowndown: 20, spriteSkillList: ["56827","56827"], targetArea: "single" }),
  "Transformar": new Skill({ name: "Transformar", type: "utility", element: "normal", power: 20, cowndown: 25, spriteSkillList: ["56827","56827"], targetArea: "single" })
};
